# This is a basic workflow to help you get started with Actions
name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.inggritnia17 }}/simple-flask-app:${{ github.sha }} .
        docker push ${{ secrets.inggritnia17 }}/simple-flask-app:${{ github.sha }}

    - name: Push to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.inggritnia17 }}
        password: ${{ secrets.inggrit.17 }}

    - name: Push lightweight tag to Docker Hub
      run: |
        docker tag ${{ secrets.inggritnia17 }}/simple-flask-app:${{ github.sha }} ${{ secrets.inggritnia17 }}/simple-flask-app:latest
        docker push ${{ secrets.inggritnia17 }}/simple-flask-app:latest
